apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubectl-client
  name: kubectl-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl-client
  template:
    metadata:
      labels:
        app: kubectl-client
    spec:
      containers:
      - args:
        - while true; do sleep 3600; done;
        command:
        - /bin/bash
        - -c
        - --
        image: dogkeeper886/kubectl-client
        imagePullPolicy: IfNotPresent
        name: kubectl-client
      serviceAccount: kubectl-client
      serviceAccountName: kubectl-client
